trigger:
  branches:
    include:
      - main


pool:
  name: 'Torneos Api Quality Control'

variables:
  - group: TORNEOS_API
stages:
  - stage: CI
    displayName: 'Continuous Integration'
    jobs:
      - job: BuildJob
        displayName: 'Build'
        variables:
          jobName: 'Integration'
        steps:

          - task: Gradle@3
            inputs:
              tasks: 'build test --tests ParallelRunner $(commandVariables) --info'
              publishJUnitResults: false
              sonarQubeRunAnalysis: true
              sqGradlePluginVersionChoice: 'specify'
              sonarQubeGradlePluginVersion: '3.0'
            displayName: "Gradle"

          - task: SonarCloudPublish@1
            inputs:
              displayName: 'Publish results on build summary'
              pollingTimeoutSec: '300'

          - task: sonarcloud-buildbreaker@2
            inputs:
              SonarCloud: 'SonarCloudGH'
              organization: 'nequiti'

          - task: PublishCucumberReport@1
            displayName: 'Publish Cucumber Report'
            inputs:
              jsonDir: '$(setRutaTask.rutaIntegracion)/build/karate-reports'
              outputPath: '$(setRutaTask.rutaIntegracion)/target/cucumber-html-reports'
            condition: succeededOrFailed()