name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [update_from_external]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: API_TORNEOS  # ← Agregar esta línea para usar el entorno

    env:
      COMMAND_VARIABLES: ${{ vars.COMMAND_VARIABLES }}  # ← Ajustar el acceso a la variable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Run Gradle Build and Tests
        run: |
          chmod +x gradlew
          ./gradlew build test --tests ParallelRunner ${{ env.COMMAND_VARIABLES }} --info
          
      - name: Publish Cucumber Report
        run: |
          mkdir -p cucumber-reports
          cp -r build/karate-reports cucumber-reports/
        if: always()

      - name: Upload Cucumber Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: cucumber-reports/
        if: always()


      - name: Sanitize Workflow Name
        run: echo "WORKFLOW_NAME=${GITHUB_WORKFLOW// /_}" >> $GITHUB_ENV
        if: always()

      - name: Create a copy of overview-features.html as index.html
        run: cp target/cucumber-html-reports/overview-features.html target/cucumber-html-reports/index.html
        if: always()

      - name: ANY REPROT - GH Pages Push - SAME REPO
        uses: PavanMudigonda/html-reporter-github-pages@v1.4
        with:
          test_results: target/cucumber-html-reports
          keep_reports: 20
          gh_pages: gh_pages # BRANCH NAME you like
          subfolder: docs  # Level 1 Folder Structure you like
          tool_name: cucumber # Level 2 Folder Structure you like
          workflow_name: ${{ env.WORKFLOW_NAME }} # Level 3 Folder Structure you like
          env: QA  # Level 4 Folder Structure you like
          token: ${{ secrets.GH_PAT }} # Please note we need GitHub Person Access Token to perform gh pages deploy
        if: always()
