name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: API_TORNEOS  # ← Agregar esta línea para usar el entorno

    env:
      COMMAND_VARIABLES: ${{ vars.COMMAND_VARIABLES }}  # ← Ajustar el acceso a la variable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Debug Environment Variables
        run: echo "COMMAND_VARIABLES=$COMMAND_VARIABLES"

      - name: Run Gradle Build and Tests
        run: |
          chmod +x gradlew
          ./gradlew build test --tests ParallelRunner ${{ env.COMMAND_VARIABLES }} --info
          
      - name: Publish Cucumber Report
        run: |
          mkdir -p cucumber-reports
          cp -r build/karate-reports cucumber-reports/
        if: always()

      - name: Cucumber HTML Report Generator
        uses: mt185252/cucumber-html-report-generator@v1
        with:
          json-file-path: cucumber-reports/cucumber.json  # 🟢 Especifica el archivo JSON correcto
          report-theme: hierarchy
          report-suite-as-scenarios: true
          scenario-timestamp: true
          failed-summary-report: true
          

      - name: Upload Cucumber Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: cucumber-reports/
    

