name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: API_TORNEOS  # ← Agregar esta línea para usar el entorno

    env:
      COMMAND_VARIABLES: ${{ vars.COMMAND_VARIABLES }}  # ← Ajustar el acceso a la variable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Debug Environment Variables
        run: echo "COMMAND_VARIABLES=$COMMAND_VARIABLES"

      - name: Run Gradle Build and Tests
        run: |
          chmod +x gradlew
          ./gradlew build test --tests ParallelRunner ${{ env.COMMAND_VARIABLES }} --info
          
      - name: Publish Cucumber Report
        run: |
          mkdir -p cucumber-reports
          cp -r build/karate-reports cucumber-reports/
        if: always()

      - name: Debug Karate Report Files
        run: ls -lR build/karate-reports

      - name: Debug Karate Target
        run: ls -lR target/cucumber-html-reports


      - name: Render Localized HTML
        # You may pin to the exact commit or the version.
        # uses: dustuu/Dustuu.Actions.RenderLocalizedHtml@254307c4ffe0ed751eb23844a48870d5bb018c33
        uses: dustuu/Dustuu.Actions.RenderLocalizedHtml@0.0.1
        with:
          # The root directory to upload from (relative to workspace). Example, "path/to/build/artifacts".
          directory: target/cucumber-html-reports/

      - name: Upload Cucumber Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: cucumber-reports/
          
    
