name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: API_TORNEOS

    env:
      COMMAND_VARIABLES: ${{ vars.COMMAND_VARIABLES }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Debug Environment Variables
        run: echo "COMMAND_VARIABLES=$COMMAND_VARIABLES"

      - name: Run Gradle Build and Tests
        run: |
          chmod +x gradlew
          ./gradlew build test --tests ParallelRunner ${{ env.COMMAND_VARIABLES }} --info
          
      - name: Move report to root
        run: cp target/cucumber-html-reports/overview-features.html ./index.html

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber-HTML-Report
          path: index.html

      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'index.html'
          job_summary: true

      - name: Comment with Preview Link
        uses: mshick/add-pr-comment@v2
        with:
          message: "✅ [View Karate Report](${{ steps.html_preview.outputs.url }})"
